# -*- coding: utf-8 -*-
"""Python-programming_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z4pDvq5LiD4VKnHGm3kaoKHG1ji7coc-

# Python programming

## Lab 1

[source](https://learn-eu-central-1-prod-fleet01-xythos.content.blackboardcdn.com/58bb1752f3dab/3631290?X-Blackboard-Expiration=1613703600000&X-Blackboard-Signature=U5NztfXIyZGvaJlqJ9FZ7rLpV%2FyKI%2BRBUQUv4%2FLW1rw%3D&X-Blackboard-Client-Id=333455&response-cache-control=private%2C%20max-age%3D21600&response-content-disposition=inline%3B%20filename%2A%3DUTF-8%27%27Lab%25201%25281%2529.pdf&response-content-type=application%2Fpdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210218T210000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Credential=AKIAZH6WM4PL5M5HI5WH%2F20210218%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Signature=b0c8d16f8d4ab6ae5ed62e6a1425247847a999f943cabdb8ccdc2945bf17346d)<br>
[Starting out with Python 3rd edition](https://gist.github.com/jendiamond/d05b8b0828c374aad1ca)

## Exercise 1: **Miles Converter**

Write a program that asks the user to enter a distance in *miles*, then converts that distance to *Kilometer* and present the kilometers.<br>
The conversion formula is as follows: Miles=Kilometers×0.6214
"""

# 1. input distance in miles
distMl = int(input('Enter a distance (in miles): '))


# 2. convert miles to kilometers
distKm = distMl * 0.6214

# using the format specifier "%" to print distKm value till 2 decimal places
print("The distance is", "%.2f" % distKm, "in km")

"""## Exercise 2: **Property Tax**

A county collects property taxes on the assessment value of property, which is 60 percent of the property’s actual value.
For example, if an acre of land is valued at USD 10,000, its assessment value is USD 6,000.
The property tax is then 72¢ for each USD 100 of the assessment value. The tax for the acre assessed at USD 6,000 will be USD 43.20.<br>
Write a program that asks for the actual value of a piece of property and displays the assessment value and property tax.
"""

# define the main function, here called tax for property tax
def tax():
    # Input the property's value
    propValue = int(input("Enter the property's value: "))
    prop(propValue)

## property's actual value is function of assessment value
def prop(propValue):
    # Evaluate the property's assessment value as 60% * actual value
    assessValue = propValue * 0.6
    print('The assessment value is $%.2f' % assessValue)
    assess(assessValue)

## Property's assessment value is function of property tax
def assess(assessValue):
    # Calculate the property tax as $0.72 every $100 (0.72/100) of assessValue
    propTax = assessValue * 0.0072
    print('The property tax is $%.2f' % propTax)

# Call the tax function.
tax()

#%tb

"""## Exercise 3: **Maximum of Two Values**

Write a function named my_max that accepts two integer values as arguments
and returns the value that is the greater of the two.<br>
For example, if 12 and 19 are passed as arguments to the function, the function should return 19. Use the function in a program that prompts the user to enter two integer values. The program should display the value that is the greater of the two.
"""

# enter the two integers
int1 = int(input('Enter a first number: '))
int2 = int(input('Enter a second number: '))

# define the my_max function that compares the two integers
# and return the greater of the two
def my_max(int1, int2):
    if int1 > int2:
        print(int1, 'is bigger than', int2)
    else:
        print(int2, 'is bigger than', int1)
my_max(int1, int2)

"""## Exercise 4: **Test Average and Grade**

Write a program that asks the user to enter five test scores. The program should display a letter grade for each score and the average test score.<br>
Write the following functions in the program:
- calc_average This function should accept five test scores as arguments
and return the average of the scores.
- determine_grade This function should accept a test score as an argument and return a letter grade for the score based on the following grading scale:

Score Letter | Grade |
--- | --- |
90-100 | A |
 |  |
80-89 | B |
 |  |
70-79 | C |
 |  |
60-69 | D |
 |  |
Below 60 | F |
"""

# define function calc_average
def calc_average():
  total = 0
  for tests in range(5):
    score = int(input('Enter a test Score: '))
    total += score
  avg = total / 5
  #return avg
  print('Average of the scores: ', avg)

calc_average()

import sys

def determine_grade():
  Score = 0
  while Score in range(5):
    score = int(input('Enter a test Score: '))
    if score >= 90 and score <= 100:
      print("Grade: A")
    elif score >= 80 and score < 90:
      print("Grade: B")
    elif score >= 70 and score < 80:
      print("Grade: C")
    elif score >= 60 and score < 70:
      print("Grade: D")
    elif score <= 59:
      print("Grade: F")
    else:
      input("Press enter to exit.")
      sys.exit()

determine_grade()